name: Context Demo

on:
  push:

  workflow_dispatch:

jobs:
    build: 
      name: "Context Demo JOB"
      runs-on: ubuntu-latest
      
      steps:
        - name: Contexto de GitHub
          run: | 
            echo "Repositorio: ${{github.repository}}"
            echo "Rama: ${{github.ref_name}}"
            echo "Commit: ${{github.sha}}"
            echo "Actor: ${{github.actor}}
            echo "Evento: ${{github.event_name}}"
          
        - name: Contexto runner
          run: |
           echo "Sistema Operativo del runner: ${{runner.os}}"
           echo "Directorio: ${{runner.temp}}"
