name: Secrets DEMO

# Controls when the workflow will run
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Jobs secrets
  uso-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Usar el secret
        run: echo "Valor del token ${{secrets.API_TOKEN}}"

      - name: Usar el secret en una variable de retorno
        env:
          TOKEN: ${{secrets.API_TOKEN}}
        run: |
          echo "El token tiene $(echo -n "$TOKEN" | wc -c) caracteres"
          echo"Valor enmascarado: $TOKEN"
